<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGk4P87H\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGk4P87H/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGk4P87H.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGk4P87H\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGk4P87H\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Gk4P87H',
    'container.build_id' => 'c3693dd3',
    'container.build_time' => 1551354619,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGk4P87H');
