<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExnfMxE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExnfMxE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerExnfMxE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerExnfMxE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerExnfMxE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ExnfMxE',
    'container.build_id' => '8e0f49b1',
    'container.build_time' => 1550849317,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExnfMxE');
