<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'liip_imagine.service.filter' shared service.

include_once $this->targetDirs[3].'/vendor/liip/imagine-bundle/Service/FilterService.php';

return $this->privates['liip_imagine.service.filter'] = new \Liip\ImagineBundle\Service\FilterService(($this->services['liip_imagine.data.manager'] ?? $this->load('getLiipImagine_Data_ManagerService.php')), ($this->services['liip_imagine.filter.manager'] ?? $this->load('getLiipImagine_Filter_ManagerService.php')), ($this->services['liip_imagine.cache.manager'] ?? $this->getLiipImagine_Cache_ManagerService()), ($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
