<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.core.flashmessage.manager' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Twig/Status/StatusClassRendererInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Twig/FlashMessage/FlashManager.php';

return $this->services['sonata.core.flashmessage.manager'] = new \Sonata\CoreBundle\FlashMessage\FlashManager(($this->services['session'] ?? $this->load('getSessionService.php')), ($this->services['translator'] ?? $this->getTranslatorService()), ['success' => ['success' => ['domain' => 'SonataCoreBundle'], 'sonata_flash_success' => ['domain' => 'SonataAdminBundle'], 'sonata_user_success' => ['domain' => 'SonataUserBundle'], 'fos_user_success' => ['domain' => 'FOSUserBundle']], 'warning' => ['warning' => ['domain' => 'SonataCoreBundle'], 'sonata_flash_info' => ['domain' => 'SonataAdminBundle']], 'danger' => ['error' => ['domain' => 'SonataCoreBundle'], 'sonata_flash_error' => ['domain' => 'SonataAdminBundle'], 'sonata_user_error' => ['domain' => 'SonataUserBundle']]], ['success' => 'success', 'warning' => 'warning', 'danger' => 'danger']);
