<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.search.handler' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Search/SearchHandler.php';

return $this->services['sonata.admin.search.handler'] = new \Sonata\AdminBundle\Search\SearchHandler(($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService()), true);
