<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.core.slugify.cocur' shared service.

@trigger_error('The "sonata.core.slugify.cocur" service is deprecated. You should stop using it, as it will be removed in the future.', E_USER_DEPRECATED);

return $this->services['sonata.core.slugify.cocur'] = new \Cocur\Slugify\Slugify();
