<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.sidebar_menu' shared service.

include_once $this->targetDirs[3].'/vendor/knplabs/knp-menu/src/Knp/Menu/ItemInterface.php';
include_once $this->targetDirs[3].'/vendor/knplabs/knp-menu/src/Knp/Menu/MenuItem.php';

return $this->services['sonata.admin.sidebar_menu'] = ($this->services['sonata.admin.menu_builder'] ?? $this->load('getSonata_Admin_MenuBuilderService.php'))->createSidebarMenu();
