<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.type.choice' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/Core/Type/ChoiceType.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ChoiceList/Factory/ChoiceListFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ChoiceList/Factory/CachingFactoryDecorator.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ChoiceList/Factory/PropertyAccessDecorator.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ChoiceList/Factory/DefaultChoiceListFactory.php';

return $this->privates['form.type.choice'] = new \Symfony\Component\Form\Extension\Core\Type\ChoiceType(new \Symfony\Component\Form\ChoiceList\Factory\CachingFactoryDecorator(new \Symfony\Component\Form\ChoiceList\Factory\PropertyAccessDecorator(new \Symfony\Component\Form\ChoiceList\Factory\DefaultChoiceListFactory(), ($this->privates['property_accessor'] ?? $this->getPropertyAccessorService()))));
