<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_imagine.data.manager' shared service.

include_once $this->targetDirs[3].'/vendor/liip/imagine-bundle/Imagine/Data/DataManager.php';

$this->services['liip_imagine.data.manager'] = $instance = new \Liip\ImagineBundle\Imagine\Data\DataManager(($this->privates['liip_imagine.binary.mime_type_guesser'] ?? $this->load('getLiipImagine_Binary_MimeTypeGuesserService.php')), ($this->privates['liip_imagine.extension_guesser'] ?? $this->load('getLiipImagine_ExtensionGuesserService.php')), ($this->privates['liip_imagine.filter.configuration'] ?? ($this->privates['liip_imagine.filter.configuration'] = new \Liip\ImagineBundle\Imagine\Filter\FilterConfiguration([]))), 'default', NULL);

$instance->addLoader('default', ($this->services['liip_imagine.binary.loader.default'] ?? $this->load('getLiipImagine_Binary_Loader_DefaultService.php')));

return $instance;
