<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.core.form.type.date_picker' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Form/Type/BasePickerType.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Form/Type/DatePickerType.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Form/Date/MomentFormatConverter.php';

return $this->services['sonata.core.form.type.date_picker'] = new \Sonata\Form\Type\DatePickerType(($this->privates['sonata.core.date.moment_format_converter'] ?? ($this->privates['sonata.core.date.moment_format_converter'] = new \Sonata\CoreBundle\Date\MomentFormatConverter())), ($this->services['translator'] ?? $this->getTranslatorService()));
