<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.admin.menu.group_provider' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Menu/Provider/GroupMenuProvider.php';

return $this->privates['sonata.admin.menu.group_provider'] = new \Sonata\AdminBundle\Menu\Provider\GroupMenuProvider(($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php')), ($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService()), ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()));
